<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Isabel Holm">

<title>Insurance Costs – Analysis of Factors Related to Costs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="insurance_costs_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="insurance_costs_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="insurance_costs_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="insurance_costs_report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="insurance_costs_report_files/libs/quarto-html/popper.min.js"></script>
<script src="insurance_costs_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="insurance_costs_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="insurance_costs_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="insurance_costs_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="insurance_costs_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="insurance_costs_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="insurance_costs_report_files/libs/bootstrap/bootstrap-514981598f886405bc67e039c5001fd5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Insurance Costs – Analysis of Factors Related to Costs</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Isabel Holm </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report presents an analysis of insurance cost data with the aim of identifying which factors are most strongly associated with individual insurance charges. The dataset contains information on customer demographics, lifestyle factors, health-related variables, and insurance history.</p>
<p>The purpose of this analysis is twofold: first, to explore and describe patterns in the data through statistical summaries and visualizations; and second, to build regression models that can help explain variation in insurance costs and potentially serve as a support tool in future pricing decisions.</p>
<p>The data set contains information about <strong>customer_id, age, sex, region, bmi, children, smoker, chronic_condition, exercise_level, plan_type, prior_accidents, prior_claims, annual_checkups</strong> and <strong>charges</strong>.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p>The analysis was conducted in R and structured across three main stages: data preparation, descriptive analysis, and regression modeling.</p>
<section id="data-preparations" class="level3">
<h3 class="anchored" data-anchor-id="data-preparations">Data Preparations</h3>
<p>The data set was loaded using the <code>readr</code> package and initially inspected using <code>glimpse()</code> and <code>summary()</code> to understand its structure and variable types. Missing values were identified in three variables: <strong>bmi</strong> (28 missing), <strong>exercise_level</strong> (22 missing), and <strong>annual_checkups</strong> (20 missing). Missing values were handled individually with the planned regression analysis in mind. For each variable containing missing observations, a missingness indicator variable was created, followed by imputation. Missing values in <strong>bmi</strong> and <strong>annual_checkups</strong> were imputed using the median, while missing values in <strong>exercise_level</strong> were replaced with <em>“Unknown”</em>.</p>
<p>Further, categorical variables were standardized by trimming whitespace and applying consistent title case formatting, before being converted to factors. A new ordered variable, <code>age_group</code>, was created by binning age into five intervals (18–30, 31–40, 41–50, 51–60, 61–75) to support group-level comparisons in the descriptive analysis. In addition, a derived variable, <code>risk_group</code>, was created to capture combined risk based on prior insurance history. This variable combines <em>prior_claims</em> and <em>prior_accidents</em> into a single categorical measure. Policyholders with no prior claims or accidents were classified as <strong>Low</strong> risk, those with two or more claims or accidents as <strong>High</strong> risk, and all others as <strong>Medium</strong> risk.</p>
</section>
<section id="descriptive-analysis" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-analysis">Descriptive Analysis</h3>
<p>Summary statistics for the target variable <strong>charges</strong> were computed, including mean, median, standard deviation, min, max, and interquartile range. A range of visualizations were also produced using <code>ggplot2</code> to explore the distribution of charges and its relationship with key variables. In the result section, only the visuals showing the strongest predictors will be displayed and discussed. However, the other variables that are not among the strongest predictors on their own may still contribute to the regression models.</p>
</section>
</section>
<section id="statistical-summary" class="level2">
<h2 class="anchored" data-anchor-id="statistical-summary">Statistical summary</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>costs <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_charges       =</span> <span class="fu">n</span>(),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_charges    =</span> <span class="fu">mean</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_charges  =</span> <span class="fu">median</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_charges      =</span> <span class="fu">sd</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_charges     =</span> <span class="fu">min</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_charges     =</span> <span class="fu">max</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">iq_r_charges    =</span> <span class="fu">IQR</span>(charges, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols      =</span> <span class="fu">everything</span>(),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to  =</span> <span class="st">"Statistic"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Value"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n_charges</td>
<td style="text-align: right;">1100</td>
</tr>
<tr class="even">
<td style="text-align: left;">mean_charges</td>
<td style="text-align: right;">10060</td>
</tr>
<tr class="odd">
<td style="text-align: left;">median_charges</td>
<td style="text-align: right;">9124</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd_charges</td>
<td style="text-align: right;">4574</td>
</tr>
<tr class="odd">
<td style="text-align: left;">min_charges</td>
<td style="text-align: right;">1204</td>
</tr>
<tr class="even">
<td style="text-align: left;">max_charges</td>
<td style="text-align: right;">32559</td>
</tr>
<tr class="odd">
<td style="text-align: left;">iq_r_charges</td>
<td style="text-align: right;">5873</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The dataset contains 1,100 observations. Insurance charges range from 1,204 to 32,559, with a mean of 10,060 and a median of 9,124. The gap between the mean and median suggests a right-skewed distribution, where a smaller number of high-charge customers pull the average upward. The standard deviation of 4,574 and an interquartile range of 5,873 indicate considerable spread in charges across the dataset.</p>
<section id="distribution-of-charges" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-charges">Distribution of charges</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> charges)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">"turquoise"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of insurance charges"</span>, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Charges"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/distribution%20of%20charges-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram confirms the right-skewed distribution noted in the summary statistics. The majority of customers have charges clustered between approximately 4,000 and 13,000, with a long tail extending toward the higher end. This suggests that while most customers incur moderate costs, a smaller group generates significantly higher charges.</p>
</section>
<section id="charges-per-group" class="level3">
<h3 class="anchored" data-anchor-id="charges-per-group">Charges per group</h3>
<section id="charges-by-insurance-plan-type" class="level4">
<h4 class="anchored" data-anchor-id="charges-by-insurance-plan-type">Charges by insurance plan type</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> plan_type, <span class="at">y =</span> charges, <span class="at">fill =</span> plan_type)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Charges by insurance plan type"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Charges"</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Charges%20by%20insurance%20plan%20type-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Charges by insurance plan type show that Premium plan customers tend to have somewhat higher median charges compared to Basic and Standard customers. The Standard plan displays the widest spread and the most outliers at the upper end, suggesting greater variability in costs among that group. The difference between plan types is moderate, indicating that plan type alone may not be a strong standalone predictor of charges.</p>
</section>
<section id="charges-by-smoking-status" class="level4">
<h4 class="anchored" data-anchor-id="charges-by-smoking-status">Charges by smoking status</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> smoker, <span class="at">y =</span> charges, <span class="at">fill =</span> smoker)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Charges by smoking status"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Charges"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Charges%20by%20smoking%20status-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Smoking status shows one of the clearest group differences in the dataset. Smokers have a considerably higher median charge of around 16,000 compared to approximately 8,000 for non-smokers. The interquartile range for smokers also sits entirely above the median for non-smokers, indicating that even typical smoker costs exceed what most non-smokers pay. This suggests smoking is likely to be one of the stronger predictors in the regression model.</p>
</section>
<section id="charges-by-chronic-condition" class="level4">
<h4 class="anchored" data-anchor-id="charges-by-chronic-condition">Charges by chronic condition</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> chronic_condition, <span class="at">y =</span> charges, <span class="at">fill =</span> chronic_condition)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Charges by chronic condition status"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Charges"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Charges%20by%20chronic%20condition-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Customers with a chronic condition show notably higher charges than those without, with a median of around 13,000 compared to approximately 8,000 for the non-chronic group. The spread among chronic condition customers is also tighter, suggesting a more consistent cost pattern within that group. This points to chronic condition status as another likely significant predictor in the regression model.</p>
</section>
<section id="charges-by-age-group" class="level4">
<h4 class="anchored" data-anchor-id="charges-by-age-group">Charges by age group</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> age_group, <span class="at">y =</span> charges, <span class="at">fill =</span> age_group)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Charges by age group"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Charges"</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Charges%20by%20age%20group-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Charges show a clear upward trend across age groups, with median charges rising steadily from around 8,000 in the 18–30 group to approximately 12,000 in the 61-75 group. The spread also widens in older groups, particularly in the 61-75 bracket, suggesting greater variability in costs among older customers. This pattern aligns with the expectation that age is positively associated with insurance charges and indicates it will likely be a meaningful predictor in the regression model.</p>
</section>
<section id="charges-by-risk-group" class="level4">
<h4 class="anchored" data-anchor-id="charges-by-risk-group">Charges by risk group</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> risk_group, <span class="at">y =</span> charges, <span class="at">fill =</span> risk_group)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Charges by risk group"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Charges"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Charges%20by%20risk%20group-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Customers were grouped into three risk categories based on their claims and accident history. The boxplot shows a clear stepwise pattern, with <strong>High</strong> risk customers having a median charge of around 14,000, followed by <strong>Medium</strong> at approximately 10,000 and <strong>Low</strong> at around 8,000. This suggests that prior claims and accident history combined into a single risk group variable is a meaningful way to capture customer risk and is likely to be a relevant predictor in the regression model.</p>
<p>It should be noted however that the thresholds used to define the groups are manually set and somewhat arbitrary, different cutoff values could produce different groupings and potentially lead to different conclusions.</p>
</section>
</section>
<section id="continuous-predictors-and-charges" class="level3">
<h3 class="anchored" data-anchor-id="continuous-predictors-and-charges">Continuous predictors and charges</h3>
<section id="age-against-charges-with-smoking-status" class="level4">
<h4 class="anchored" data-anchor-id="age-against-charges-with-smoking-status">Age against charges with smoking status</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> charges, <span class="at">color =</span> smoker)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"tomato"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Age vs insurance charges (with smoking status)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Age%20vs%20charges%20(with%20smoker%20status)-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot of age against charges, colored by smoking status, reveals two fairly distinct clusters. Smokers consistently occupy the upper portion of the chart across all age groups, while non-smokers cluster at lower charge levels. The overall trend line shows a positive relationship between age and charges, but the separation between smokers and non-smokers suggests that smoking status may have a stronger influence on charges than age alone.</p>
</section>
<section id="age-against-charges-with-chronic-condition" class="level4">
<h4 class="anchored" data-anchor-id="age-against-charges-with-chronic-condition">Age against charges with chronic condition</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> charges, <span class="at">color =</span> chronic_condition)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"tomato"</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Age vs insurance charges (with chronic condition)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Age%20vs%20charges%20(with%20chronic%20condition%20status)-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When grouping by chronic condition, the separation between groups is less pronounced than with smoking status. Customers with a chronic condition tend to have somewhat higher charges, but there is considerable overlap between the two groups. The positive relationship between age and charges holds regardless of chronic condition status.</p>
</section>
<section id="bmi-against-charges" class="level4">
<h4 class="anchored" data-anchor-id="bmi-against-charges">Bmi against charges</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(costs, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"tomato"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bmi vs insurance charges"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Bmi%20vs%20charges-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>BMI against charges shows a weaker positive relationship, with the trend line indicating that charges increase slightly as BMI rises. However, the considerable spread of points around the trend line suggests that BMI alone is a relatively weak predictor of charges. It may still contribute to the regression model, but is unlikely to be among the strongest predictors on its own.</p>
</section>
</section>
</section>
<section id="regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="regression-analysis">Regression analysis</h2>
<p>To predict insurance charges, three linear regression models were built using <code>lm()</code>. The models were constructed progressively, starting simple and adding complexity stepwise, in order to evaluate whether additional variables and interactions improved predictive performance.</p>
<p>The descriptive analysis indicated that three variables had a particularly strong relationship with charges: <code>smoker</code>, <code>chronic_condition</code>, and <code>age</code>. These were included in all three models as the core predictors.</p>
<ul>
<li><strong>Model 1:</strong> includes only these three strong predictors and serves as a baseline for comparison.</li>
<li><strong>Model 2:</strong> extends the baseline by adding <code>bmi</code>, <code>risk_group</code>, <code>plan_type</code>, and <code>exercise_level</code>. These variables were selected based on their theoretical relevance to insurance costs, and although their relationship with charges was weaker than the core predictors, the descriptive analysis indicated a positive association worth exploring further.</li>
<li><strong>Model 3:</strong> builds on Model 2 by adding an interaction term between <code>age</code> and <code>smoker</code>, based on the hypothesis that the cost of smoking may increase with age. An interaction term lets the model capture that.</li>
</ul>
<p>Variables such as <code>sex</code>, <code>region</code>, and <code>annual_checkups</code> were excluded to keep the model interpretable, and because their theoretical link to individual charges was considered weaker or more ambiguous.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> smoker <span class="sc">+</span> chronic_condition, <span class="at">data =</span> costs)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">+</span> smoker <span class="sc">+</span> chronic_condition <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>               bmi <span class="sc">+</span> risk_group <span class="sc">+</span> plan_type <span class="sc">+</span> exercise_level,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> costs)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> age <span class="sc">*</span> smoker <span class="sc">+</span> chronic_condition <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>               bmi <span class="sc">+</span> risk_group <span class="sc">+</span> plan_type <span class="sc">+</span> exercise_level,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> costs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model comparison</h3>
<p>The three models are compared against each other using adjusted R² and AIC (Akaike Information Criterion). Adjusted R² measures how well the model explains the variation in insurance charges, expressed as a value between 0 and 1 where a higher value indicates a better fit. Unlike regular R², it adjusts for the number of predictors, meaning it only increases if a new variable actually improves the model.</p>
<p>AIC balances how well the model is fitted against model complexity, where a lower value indicates a better model. It is particularly useful when comparing models of different sizes, as it penalises unnecessary complexity.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model   =</span> <span class="fu">c</span>(<span class="st">"Model 1"</span>, <span class="st">"Model 2"</span>, <span class="st">"Model 3"</span>),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">adj_r2  =</span> <span class="fu">c</span>(<span class="fu">summary</span>(model1)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summary</span>(model2)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summary</span>(model3)<span class="sc">$</span>adj.r.squared),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">aic     =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(model1), <span class="fu">AIC</span>(model2), <span class="fu">AIC</span>(model3))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Adjusted R²"</span>, <span class="st">"AIC"</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Model comparision - Adjusted R² and AIC"</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model comparision - Adjusted R² and AIC</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Adjusted R²</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model 1</td>
<td style="text-align: right;">0.663</td>
<td style="text-align: right;">20474</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 2</td>
<td style="text-align: right;">0.741</td>
<td style="text-align: right;">20192</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model 3</td>
<td style="text-align: right;">0.741</td>
<td style="text-align: right;">20194</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Adjusted R²:</strong> Model 1 explains about 66% of the variation in insurance charges using only the three strong predictors. Model 2 jumps to 74% by adding BMI, risk group, plan type and exercise level, which is a meaningful improvement. Model 3 stays at 74%, meaning the interaction term between age and smoker didn’t add any real explanatory value beyond model 2.</p>
<p><strong>AIC:</strong> Model 1 has the highest AIC, confirming it’s the weakest fit. Model 2 scores only slightly lower at 20 192 and Model 3 scores just above at 20 194, so once again the interaction term in Model 3 didn’t improve the fit enough to justify it.</p>
<p><strong>Overall conclusion:</strong> Model 2 is the best model. It explains noticeably more than Model 1, and the interaction between age and smoking that Model 3 tests turns out not to be necessary, at least not in this data set.</p>
</section>
<section id="model-2---detailed-results" class="level3">
<h3 class="anchored" data-anchor-id="model-2---detailed-results">Model 2 - Detailed Results</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + smoker + chronic_condition + bmi + 
    risk_group + plan_type + exercise_level, data = costs)

Residuals:
    Min      1Q  Median      3Q     Max 
-8941.5 -1498.2  -102.6  1410.4 17583.5 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            1207.006    590.651   2.044  0.04124 *  
age                      70.761      5.723  12.365  &lt; 2e-16 ***
smokerYes              7422.828    184.187  40.300  &lt; 2e-16 ***
chronic_conditionYes   3790.921    166.658  22.747  &lt; 2e-16 ***
bmi                     158.666     15.653  10.136  &lt; 2e-16 ***
risk_groupLow         -2618.188    316.933  -8.261 4.16e-16 ***
risk_groupMedium      -1456.807    329.000  -4.428 1.05e-05 ***
plan_typePremium       1483.612    207.563   7.148 1.61e-12 ***
plan_typeStandard       670.358    161.186   4.159 3.45e-05 ***
exercise_levelLow      1487.758    211.500   7.034 3.53e-12 ***
exercise_levelMedium    512.796    189.573   2.705  0.00694 ** 
exercise_levelUnknown   655.105    524.030   1.250  0.21152    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2328 on 1088 degrees of freedom
Multiple R-squared:  0.7436,    Adjusted R-squared:  0.741 
F-statistic: 286.8 on 11 and 1088 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Model 2 explains 74% of the variation in insurance charges, and the overall model is highly significant (p &lt; 0.001). All included predictors were statistically significant, suggesting that each variable contributes meaningfully to predicting charges.</p>
<p><strong>The strongest individual predictor was <em>smoking status</em>,</strong> where smokers on average incur approximately 7 423 higher charges than non-smokers. Having a <em>chronic condition</em> adds around 3 791 to charges, and each additional year of age increases charges by approximately 71. BMI also shows a positive effect, with each unit increase adding around 159 to charges.</p>
<p>Regarding <em>risk group</em>, policyholders classified as Low or Medium risk have notably lower charges compared to the High risk reference group, with Low risk customers having charges around 2 618 less. Customers on a Premium plan have charges around approximately 1 484 more than the Basic plan, and those with a Standard plan around 670 more. Finally, <em>exercise level</em> shows that lower activity is associated with higher charges, with Low exercise adding around 1 488 compared to the High exercise group.</p>
<p><em>Note that in all interpretations are made on the basis that each coefficient reflects the effect of that variable while holding all others constant.</em></p>
<section id="residual-vs-fitted" class="level4">
<h4 class="anchored" data-anchor-id="residual-vs-fitted">Residual vs fitted</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model2$model manages NA as it only contains the rows lm() actually used</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model2_diagnostics <span class="ot">&lt;-</span> model2<span class="sc">$</span>model <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fitted_value =</span> <span class="fu">fitted</span>(model2),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">residual     =</span> <span class="fu">residuals</span>(model2)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model2_diagnostics, <span class="fu">aes</span>(<span class="at">x =</span> fitted_value, <span class="at">y =</span> residual)) <span class="sc">+</span> </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"tomato"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model 2"</span>, <span class="at">x =</span> <span class="st">"Fitted values"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Residual%20vs%20fitted%20-%20Model%202-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals are roughly centered around zero, which is a good sign. However, the spread increases as fitted values get larger.This means the model is less precise at predicting higher charges, which is worth noting as a limitation. A few outliers with large residuals are also visible, particularly in the mid-to-high range.</p>
</section>
<section id="qq-plot" class="level4">
<h4 class="anchored" data-anchor-id="qq-plot">QQ-plot</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model2))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(model2), <span class="at">col =</span> <span class="st">"tomato"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/QQ-plot%20-%20Model%202-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals follow the reference line closely through the middle of the distribution, suggesting approximate normality for most observations. However, both tails deviate from the line. This indicates that the model tends to underestimate some very low charges and overestimate some very high ones.</p>
</section>
<section id="actual-vs-predicted-charges" class="level4">
<h4 class="anchored" data-anchor-id="actual-vs-predicted-charges">Actual vs predicted charges</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (model2_diagnostics, <span class="fu">aes</span>(<span class="at">x =</span> charges, <span class="at">y =</span> fitted_value)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"tomato"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model 2 - Actual vs Predicted"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Actual charges"</span>, <span class="at">y =</span> <span class="st">"Predicted charges"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="insurance_costs_report_files/figure-html/Actual%20vs%20predicted%20charges%20-%20Model%202-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Points close to the dashed reference line indicate accurate predictions. The model performs well in the low-to-mid charge range, where most points follow the line closely. However, at higher actual charge levels the predictions become less accurate. The model tends to underpredict high charges, as seen by points falling below the reference line in the upper range.</p>
<p>A few notable outliers are also visible, particularly one observation with very high actual charges, about 32 000, that the model significantly underpredicts. Overall the plot confirms that the model captures the general pattern reasonably well, but is less reliable at the extremes.</p>
</section>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>………</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<ul>
<li><p>Linear regression assumes a straight-line relationship — charges may not behave that way</p></li>
<li><p>Right-skewed charges can violate normality assumptions (visible in QQ-plot)</p></li>
<li><p>The model can only find correlations in historical data, not causation</p></li>
<li><p>Some variables were excluded for simplicity — a real model might include them</p></li>
<li><p><code>risk_group</code> is a simplified derived variable that loses some nuance from the raw claims/accidents data</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>